### ISSUE TITLE
SNL wrong error detected

### ISSUE THREAD

**Issue by agaget** [epics-extensions/vscode-epics#13]
avec ce petit programme qui devrait marcher, il indique des errerus types "identifier undefined"

/*
 * C.E.A. IRFU/SIS/LDISC
 *
 * $Id$
 *
 * who       when      what
 * --------  --------  ----------------------------------------------
 * agaget  15/04/16  created
 */

program SequenceLoad

option -c;
%%#include <string.h>
%%#include <time.h> 
%%#include <stdlib.h>
%%#include <stdio.h>

int disconnected;
assign disconnected to "{Experiment}:Seq-Disconnected";

ss ss3
{

    state idle
    {

		when (pvConnectCount() != pvAssignCount()){
			disconnected=1;
			pvPut(disconnected);
		} state idle

		when(delay(3)){
			printf("wait 3 seconds\n");
			IsSequenceStarted=1;
			pvPut(IsSequenceStarted);
		}state DebutCycle

	}
}

**Comment by vnadot** [comment]
No bug on my computer, bug on Alexis' only.

**Comment by agaget** [comment]
Doesn't occured anymore
