### ISSUE TITLE
longout not autocomplete editing .db file

### ISSUE THREAD

**Issue by prjemian** [epics-extensions/vscode-epics#32]
**Describe the bug**
When editing a `.db` file, the `longout` record type does not appear in the autocomplete list.  Only `epics.field.lolo` and `epics.field.low`

**To Reproduce**
In the second line of file `stubborn.db`:

```
record(ao, "stubborn:A")
record(l)
```

type a `o` after the `l` and view the autocomplete list.

**Expected behavior**
Expecting `longout` to appear in the list

**Screenshots**

![Clipboard01](https://user-images.githubusercontent.com/2279984/97338264-48ee6c80-184f-11eb-8e88-08a3dcb7629e.png)

**Desktop (please complete the following information):**

`VSCode -> ./VSCode-linux-x64-stable-x64-1602601238/`

**Comment by vnadot** [comment]
Thanks, will be fix next release.

**Comment by vnadot** [comment]
Done in 32518399fb222f1c6e9f40aa269aace59d69deed
